### PR TITLE
Feature/grunt-refactor

### PR DESCRIPTION
**Pull request by allenmoore**
We have started to notice an issue with the maintainability of the Gruntfile for projects. If a project is small or if the grunt tasks are minimal, this may not be an issue. But as a project scales, and as developers introduce additional tasks, the ability to easily maintain the Gruntfile becomes increasingly difficult.

This pull requests introduces the use of individual tasks and options files, that are called via a simplified Gruntfile.js. With this approach, we can easily maintain each task and option, while reducing merge conflicts if multiple developers have edited the Gruntfile.

This pull request stems from a current project that is requiring such a workflow.

### CODE REVIEW

**Comment by Camwyn** [comment]
:+1:

**Comment by saltcod** [comment]
++++ Lots of our gruntfiles are getting longer and longer lately as we keep adding functionality and /src/*.js! ( though this is getting addressed elsewhere). 

I'm all for having functionality broken up so I can quickly add/subtract/copy for another project.

**Comment by jonathantneal** [comment]
I love this modular stuff. Let’s get it in.

**Comment by briansaycocie** [comment]
This makes a lot of sense, great work!

**Comment by zrothauser** [comment]
👍

**Pull request merged**
