### PR TITLE
Browserify, Source Maps

### PR DESCRIPTION
**Pull request by jonathantneal**
This is a major update to how JS files are handled. This does for JS what #44 does for CSS.

Added: Source maps for JS file.
Added: A custom JS variable for targeting old Internet Explorer, `OLDIE`.
Added: An alternative JS file for old Internet Explorer.
Changed: Only one minified JS file is ever used.

The ability to `require` JavaScript files from within JavaScript is going to be huge. It will make writing modular, single-purposed JS much easier since it removes the hassle of organizing files in a Grunt task and since it removes the need for an [IIFE](http://benalman.com/news/2010/11/immediately-invoked-function-expression/) wrapping around every JS file. It will also make debugging easier, as modular files and source maps allow developers to narrow errors down to the exact line on the exact JS file that is causing them.

### CODE REVIEW

**Comment by allenmoore** [comment]
+1 for this.

**Comment by tlovett1** [comment]
Seems like this PR contains #44?

**Comment by jonathantneal** [comment]
It is contingent on #44.

**Comment by tlovett1** [comment]
I see identical changes seems if we merged them both there would be conflicts.

**Comment by jonathantneal** [comment]
#45 should be ahead of #44, meaning the number of changes in #45 should be cut in half, should #44 be merged. If #44 does merge into master, I will then rebase #45 with master to ensure there are no conflicts, and also to pull in any changes that may occur in between.

**Pull request closed without merging**
