### PR TITLE
change copy task to resolve build task failure

### PR DESCRIPTION
**Pull request by allenmoore**
This resolves issue #16 where the build task fails when copy runs.

### CODE REVIEW

**Comment by allenmoore** [comment]
I saw something similar here -- http://stackoverflow.com/questions/22161119/grunt-contrib-copy-ignore-folder-when-copying.

**Comment by lkwdwrd** [comment]
Thanks for all the work you've been doing on this @allenmoore !

Quick question before merging this in. As mentioned in #6, the build tasks are a bit messy. I'm almost fine that they're broken at the moment because the resulting zip file has a bunch of things in there that shouldn't be for a built release.

Is it worth fixing the build task only to have it not work correctly and possibly end up with a lot of semi-broken zip files out there, or should we do a bit more work now to clear up #6 and fix the build task in general?

**Comment by allenmoore** [comment]
@lkwdwrd I think it would be worth the time to fix the build task so that it is functioning optimally. This is something I'll definitely be glad to take on and resolve. The build task, when working correctly, would be a great feature to have before pushing a theme/plugin/library to production or before releasing.

**Comment by lkwdwrd** [comment]
Most of the setup will be changed as part of pushing out the final V1. Closing this PR for now and we'll clean up the build task as needed then.

**Pull request closed without merging**
