### PR TITLE
Update package dependencies

### PR DESCRIPTION
**Pull request by zrothauser**

### CODE REVIEW

**Comment by jonbellah** [comment]
+1

**Comment by lkwdwrd** [comment]
Code looks good, but we need to resolve the conflicts to merge.

Also, noting we really need to refactor and write JSON as JS Objects rather than through _ templates. But that's another PR.

**Comment by lkwdwrd** [comment]
@zrothauser - any chance you can get this cleaned up so we can merge?

**Comment by zrothauser** [comment]
I think this has been taken care of by this updated PR:
https://github.com/10up/generator-wp-make/pull/44

**Comment by lkwdwrd** [comment]
@zrothauser #44 is still being worked on and may be a bit before merge. If you'd rather close this one, though, I've got some other updates coming soon that will take care of this.

**Comment by zrothauser** [comment]
Sounds good - since this was a couple months ago it's probably out of date anyway. Closing.

**Pull request closed without merging**
